import "cypress-react-selector";
describe("тестирование стека", () => {
  beforeEach(() => {
    cy.visit("http://localhost:3000/stack");
    cy.waitForReact();
    cy.get('input[placeholder="Введите текст"]').as("inputVal");
    cy.get("button").contains("Добавить").parent().as("buttonAdd");
    cy.get("button").contains("Удалить").parent().as("buttonDel");
    cy.get("button").contains("Очистить").parent().as("buttonClear");
  });
  it("проверка если инпут пуст, кнопка не доступна", () => {
    cy.get("@inputVal").should("not.have.text");
    cy.get("@buttonAdd").should("be.disabled");
    cy.get("@inputVal").type("1");
    cy.get("@buttonAdd").should("be.enabled");
    cy.get("@inputVal").type("{selectAll}");
    cy.get("@inputVal").type("{del}");
    cy.get("@buttonAdd").should("be.disabled");
  });

  it("Проверка правильности добавления элемента в стек.", () => {
    cy.get("@inputVal").type("A1");
    cy.get("@buttonAdd").click();
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "changing");
    cy.wait(500);
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(0).getProps("head").should("eq", "top");
    cy.getReact("Circle").nthNode(0).getProps("letter").should("eq", "A1");

    cy.get("@inputVal").type("B2");
    cy.get("@buttonAdd").click();
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(1).getProps("state").should("eq", "changing");
    cy.wait(500);
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(0).getProps("head").should("eq", "");
    cy.getReact("Circle").nthNode(0).getProps("letter").should("eq", "A1");
    cy.getReact("Circle").nthNode(1).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(1).getProps("head").should("eq", "top");
    cy.getReact("Circle").nthNode(1).getProps("letter").should("eq", "B2");

    cy.get("@inputVal").type("C3");
    cy.get("@buttonAdd").click();
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(1).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(2).getProps("state").should("eq", "changing");
    cy.wait(500);
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(0).getProps("head").should("eq", "");
    cy.getReact("Circle").nthNode(0).getProps("letter").should("eq", "A1");
    cy.getReact("Circle").nthNode(1).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(1).getProps("head").should("eq", "");
    cy.getReact("Circle").nthNode(1).getProps("letter").should("eq", "B2");
    cy.getReact("Circle").nthNode(2).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(2).getProps("head").should("eq", "top");
    cy.getReact("Circle").nthNode(2).getProps("letter").should("eq", "C3");
  });
  it("Проверка правильности удаление элемента из стека", () => {
    cy.get("@inputVal").type("A1");
    cy.get("@buttonAdd").click();
    cy.wait(1000);
    cy.get("@inputVal").type("B2");
    cy.get("@buttonAdd").click();
    cy.wait(1000);
    cy.get("@inputVal").type("C3");
    cy.get("@buttonAdd").click();
    cy.wait(1000);
    cy.react("Circle").should("have.length", 3);
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(1).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(2).getProps("state").should("eq", "default");
    cy.get("@buttonDel").click();
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(1).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(2).getProps("state").should("eq", "changing");
    cy.wait(1000);
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(0).getProps("head").should("eq", "");
    cy.getReact("Circle").nthNode(0).getProps("letter").should("eq", "A1");
    cy.getReact("Circle").nthNode(1).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(1).getProps("head").should("eq", "top");
    cy.getReact("Circle").nthNode(1).getProps("letter").should("eq", "B2");
    cy.react("Circle").eq(2).should("not.exist");
    cy.react("Circle").should("have.length", 2);
    cy.get("@buttonDel").click();
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(1).getProps("state").should("eq", "changing");
    cy.wait(1000);
    cy.getReact("Circle").nthNode(0).getProps("state").should("eq", "default");
    cy.getReact("Circle").nthNode(0).getProps("head").should("eq", "top");
    cy.getReact("Circle").nthNode(0).getProps("letter").should("eq", "A1");
    cy.react("Circle").eq(1).should("not.exist");
    cy.react("Circle").should("have.length", 1);
  });

  it("Проверка очистки стека", () => {
    cy.get("@inputVal").type("A1");
    cy.get("@buttonAdd").click();
    cy.wait(1000);
    cy.get("@inputVal").type("D1");
    cy.get("@buttonAdd").click();
    cy.wait(1000);
    cy.get("@inputVal").type("C1");
    cy.get("@buttonAdd").click();
    cy.wait(1000);
    cy.react("Circle").should("have.length", 3);
    cy.get("@buttonClear").click();
    cy.react("Circle").should("not.exist");
  });
});
